version: '3.8'

services:
  vape-manager:
    image: ghcr.io/billsbdb3/vape-mixing-manager:latest
    container_name: vape-juice-manager
    ports:
      - "5001:5001"
    volumes:
      - ./vape_data.json:/app/vape_data.json
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
